# Koyeb deployment configuration for QuizWise Backend
# Place this file in your project root for automatic configuration

name: quizwise-backend

services:
  - name: api
    build:
      type: buildpack
      buildpack: nodejs
    run_command: npm start
    port: 3000
    
    # Environment variables (set these in Koyeb dashboard)
    env:
      - key: GEMINI_API_KEY
        value: your_gemini_api_key_here
      - key: NODE_ENV
        value: production
    
    # Deployment settings
    regions:
      - fra  # Europe (Frankfurt) - change to was (Washington) or sin (Singapore) based on your location
    
    # Instance configuration
    instance_type: nano  # Good for starting, upgrade to micro/small as needed
    
    # Auto-scaling settings
    min_scale: 1  # Always keep at least 1 instance running
    max_scale: 3  # Scale up to 3 instances under heavy load
    
    # Health check
    health_check:
      path: /health
      port: 3000
      initial_delay_seconds: 30
      timeout_seconds: 10
      
    # Resource limits
    resources:
      memory: 512Mi  # 512MB memory
      cpu: "0.1"     # 0.1 CPU cores

# Optional: Custom domain configuration
# domains:
#   - name: api.yourdomain.com
#     service: api
